version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
#    env_file:
#      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=fastapi
      - SECRET_KEY=f6f0f4caa6cf63b88e8d66b7a9563b93f70993e709d25e094faa6ca2556c8181
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
      - POSTGRES_USER=postgres

    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: